### ISSUE TITLE
Certain pages no longer exist

### ISSUE THREAD

**Issue by taowa** [neuropoly/neuropoly-docs#12]
I'm not all that familiar with gitbook, but if SUMMARY.md is the list of all of the pages that "exist", people/ isn't present there at all, and can probably be removed to avoid confusion (see #10 then #11).

**Comment by jcohenadad** [comment]
previously, "people" (like other sections) was a proper "section", not a page. Then, it became a page, but I guess gitbook did not delete the folder.

**Comment by taowa** [comment]
This includes the software-1 directory too. Preparing a PR to fix this.

**Comment by taowa** [comment]
This bash one-liner will tell you which files don't exist under SUMMARY.md.
`for file in $(find -not -path './.git*' | cut -c 3-); do grep \($file SUMMARY.md >/dev/null || echo "$file"; done`

This gave me:
[ ] people
[ ] onboarding
[ ] software-1

I'm preparing a PR to get rid of all of those, and closing this issue in consequence.
