### ISSUE TITLE
Testing Permissions

### ISSUE THREAD

**Issue by kousu** [neuropoly/neuropoly-docs#13]
This is a test for @joshuacwnewton and my attempt to tidy up the org chart and onboarding flow in https://github.com/neuropoly/onboarding/issues/10.

Sorry for the noise @neuropoly/developers. Let me know if you get this, though :beach_umbrella:

**Comment by kousu** [comment]
Thanks for your time!

**Comment by dyt811** [comment]
I got this. I have no idea what is going on. K.
