### ISSUE TITLE
Add Twitter badge

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/neuropoly-docs#16]
It would be nice to have a "follow on twitter" badge in our website.

E.g.: just below the github link:
![image](https://user-images.githubusercontent.com/2482071/124834138-3c2d2700-df4d-11eb-95f9-3517ce27e0bf.png)

**Comment by kousu** [comment]
I don't think we can put it there. That part of the page is part of their theme. https://docs.gitbook.com/resources/gitbook-legacy/v2-differences#custom-css explains

> 1. We have moved away from the static site generator model, and no longer use `gitbook` CLI to build documentation output. 
> 2. V2 cannot be self-hosted but is a cloud solution only. You can read everything about our terms and services in our docs.
> 3. Custom CSS has lots of cons, for both authors and the varieties of use cases such as mobile, tablet, desktop and all the different states. Instead, we prefer to offer customization options that we officially support, and that is easy to use for everyone. For now you the **business plan** offers you advanced branding such as: [three useless options]

What they are expecting from us, then, is to open a https://gitbook.canny.io/feature-requests to ask for social media integration. And then they'll probably want to charge for it.

What I can do instead is add it to the front and Contact Us pages.

**Comment by kousu** [comment]
I tried

https://github.com/neuropoly/neuropoly-docs/commit/a8a5762ceed9d7b84c9572163c90bde708c142f0

but it doesn't render the button; Gitbook sanitizes `<script>` tags out of the input:

![2021-07-07-194829_1163x300_scrot](https://user-images.githubusercontent.com/987487/124841922-6afec980-df5c-11eb-944a-3410f2d9e0e4.png)

It actually mangled the input even more than that and broke the link:

```html
<a class="link-a079aa82--primary-53a25e66--link-faf6c434" style="color:#E73C3C" href="https://github.com/neuropoly/neuropoly-docs/tree/a8a5762ceed9d7b84c9572163c90bde708c142f0/”http:/twitter.com/polyNeuro″/README.md" target="_blank" rel="noopener noreferrer" data-key="8d32066ac45b4158843d1bae55c7ff4b"><span data-key="f79f643c657b4e748d9792a9e5e8281a"><span data-offset-key="f79f643c657b4e748d9792a9e5e8281a:0">Follow @polyNeuro</span></span></a>
```

I'm going to try using the badges from SCT and seeing how it takes those.

**Comment by kousu** [comment]
https://github.com/neuropoly/neuropoly-docs/commit/67617ea7134a0c027878dadcf04686b74c5e0b1f produced


![2021-07-07-195817_1012x425_scrot](https://user-images.githubusercontent.com/987487/124842561-d39a7600-df5d-11eb-9812-b91c3af5c90e.png)

That second option, where I just pasted in the `<img>` tag straight, totally got censored:

```
<p class="blockParagraph-544a408c" data-key="bd04696b9b204f939e11c81b4f490d88"><span class="text-4505230f--TextH400-3033861f--textContentFamily-49a318e1"><span data-key="70a8be41b848453ca6fcbc007fad1096"><span data-offset-key="70a8be41b848453ca6fcbc007fad1096:0">or how about</span></span></span></p>
```

**Comment by kousu** [comment]
Reversing the HTML to markdown, I did https://github.com/neuropoly/neuropoly-docs/commit/1b747fc6b35e632b3b78181a9817a856b532f4f0 which produced

![2021-07-07-200444_1564x442_scrot](https://user-images.githubusercontent.com/987487/124842878-984c7700-df5e-11eb-9043-5f867fd890a1.png)

It's a bit small but at least it's there? What do you think @jcohenadad ?

**Comment by jcohenadad** [comment]
Fixed by @kousu 😊
